# Copyright (c) 2025 MiroMind
# This source code is licensed under the Apache 2.0 License.

"""QualityManifest — computed provenance footer for swarm reports.

NOT generated by LLM — computed from SwarmMetrics and pipeline state.
Appended to every knowledge and user report as a structured provenance
section so the reader knows exactly what the pipeline did and didn't do.

Inspired by the ADK QualityManifest (apps/adk-agent/models/quality_manifest.py)
but adapted for the gossip swarm's phase structure.

Shows:
- Corpus size and section count
- Worker count and angles
- Gossip rounds executed and info gain per round
- Convergence status
- Serendipity bridge status
- Phase timing breakdown
- Total LLM calls and elapsed time
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class SwarmQualityManifest:
    """Structured provenance for a swarm synthesis run.

    All fields are computed from SwarmMetrics — no LLM involvement.

    Attributes:
        corpus_chars: Total source corpus size in characters.
        section_count: Number of detected sections in the corpus.
        worker_count: Number of specialist workers used.
        angles: List of research angles assigned to workers.
        gossip_rounds_executed: Number of gossip rounds completed.
        gossip_rounds_configured: Number of gossip rounds configured.
        gossip_converged_early: Whether gossip stopped before max rounds.
        gossip_info_gain: Information gain per round (fraction of new trigrams).
        serendipity_produced: Whether serendipity bridge found cross-angle insights.
        phase_times_s: Timing breakdown by phase in seconds.
        total_llm_calls: Total LLM API calls made.
        total_elapsed_s: Wall-clock time for the full pipeline.
        worker_input_chars: Input size per worker in characters.
        worker_output_chars: Output size per worker in characters.
        degradations: List of phase failures or fallbacks that occurred.
    """

    corpus_chars: int = 0
    section_count: int = 0
    worker_count: int = 0
    angles: list[str] = field(default_factory=list)
    gossip_rounds_executed: int = 0
    gossip_rounds_configured: int = 0
    gossip_converged_early: bool = False
    gossip_info_gain: list[float] = field(default_factory=list)
    serendipity_produced: bool = False
    phase_times_s: dict[str, float] = field(default_factory=dict)
    total_llm_calls: int = 0
    total_elapsed_s: float = 0.0
    worker_input_chars: list[int] = field(default_factory=list)
    worker_output_chars: list[int] = field(default_factory=list)
    degradations: list[str] = field(default_factory=list)

    def to_markdown(self) -> str:
        """Render the manifest as a markdown provenance section.

        Returns:
            Markdown string suitable for appending to reports.
        """
        lines = [
            "---",
            "",
            "# Provenance",
            "",
            "*This section is computed from pipeline metrics, not generated by LLM.*",
            "",
            "| Metric | Value |",
            "|--------|-------|",
            f"| Source corpus | {self.corpus_chars:,} chars |",
            f"| Sections detected | {self.section_count} |",
            f"| Workers deployed | {self.worker_count} |",
            f"| Gossip rounds | {self.gossip_rounds_executed}/{self.gossip_rounds_configured}"
            f"{' (converged early)' if self.gossip_converged_early else ''} |",
            f"| Serendipity bridge | {'produced insights' if self.serendipity_produced else 'no cross-angle surprises'} |",
            f"| Total LLM calls | {self.total_llm_calls} |",
            f"| Total elapsed time | {self.total_elapsed_s:.1f}s |",
        ]

        # Info gain per round
        if self.gossip_info_gain:
            gain_str = ", ".join(f"R{i+1}: {g:.1%}" for i, g in enumerate(self.gossip_info_gain))
            lines.append(f"| Info gain per round | {gain_str} |")

        # Phase timing
        if self.phase_times_s:
            timing_parts = []
            for phase, t in self.phase_times_s.items():
                timing_parts.append(f"{phase}: {t:.1f}s")
            lines.append(f"| Phase timing | {', '.join(timing_parts)} |")

        # Worker I/O
        if self.worker_input_chars and self.worker_output_chars:
            avg_in = sum(self.worker_input_chars) / len(self.worker_input_chars)
            avg_out = sum(self.worker_output_chars) / len(self.worker_output_chars)
            lines.append(f"| Avg worker input | {avg_in:,.0f} chars |")
            lines.append(f"| Avg worker output | {avg_out:,.0f} chars |")

        lines.append("")

        # Angles
        if self.angles:
            lines.append("**Angles analyzed:**")
            for angle in self.angles:
                lines.append(f"- {angle}")
            lines.append("")

        # Degradations
        if self.degradations:
            lines.append("**Degradations:**")
            for d in self.degradations:
                lines.append(f"- {d}")
            lines.append("")

        return "\n".join(lines)
