# Copyright (c) 2025 MiroMind
# This source code is licensed under the Apache 2.0 License.

"""SwarmSynthesisBlock -- Flock gossip swarm synthesis.

Runs the 3-phase gossip protocol (per-angle workers → peer refinement
→ queen merge) on the full corpus before the final synthesiser.
Replaces the raw atomic conditions with a pre-synthesised narrative.

Also appends the computed QualityManifest footer (Phase 4) to the
swarm output so it reaches the synthesiser agent BEFORE it runs.
"""

from __future__ import annotations

import logging

from models.pipeline_block import (
    BlockContext, BlockCriticality, BlockResult, ParamSpec,
    PipelineBlock,
)

logger = logging.getLogger(__name__)


class SwarmSynthesisBlock(PipelineBlock):
    """Pre-synthesiser swarm: gossip protocol over the corpus."""

    name = "swarm_synthesis"
    needs_corpus = True
    criticality = BlockCriticality.BEST_EFFORT
    is_looped = False

    input_specs = [
        ParamSpec(
            key="corpus_for_synthesis",
            expected_type=str,
            required=False,
            description="Raw corpus formatted for synthesiser",
        ),
    ]
    output_specs = [
        ParamSpec(
            key="corpus_for_synthesis",
            expected_type=str,
            required=False,
            description="Swarm-synthesised narrative for final synthesiser",
        ),
    ]

    async def execute(self, ctx: BlockContext) -> BlockResult:
        from callbacks.condition_manager import run_swarm_synthesis

        state = ctx.state
        swarm_report = run_swarm_synthesis(state)
        metrics: dict = {}

        if swarm_report and swarm_report.strip():
            logger.info(
                "Swarm synthesis produced %d chars", len(swarm_report),
            )
            metrics["swarm_output_length"] = len(swarm_report)
            metrics["swarm_produced"] = True
        else:
            logger.warning(
                "Swarm synthesis returned empty — final synthesiser "
                "will read the raw corpus format instead"
            )
            swarm_report = state.get("corpus_for_synthesis", "")
            metrics["swarm_output_length"] = 0
            metrics["swarm_produced"] = False

        # ── Phase 4: Quality Manifest ──
        # Append computed provenance footer to the swarm output BEFORE
        # the synthesiser agent runs, so the footer appears in the final
        # report.  NOT generated by LLM — computed from corpus + metrics.
        try:
            from models.quality_manifest import QualityManifest
            manifest = QualityManifest.from_state(state)
            footer = manifest.format_footer()
            if footer and footer.strip() and swarm_report:
                swarm_report = swarm_report + footer
                metrics["manifest_appended"] = True
                metrics["manifest_degradations"] = len(manifest.degradations)
                metrics["manifest_findings"] = manifest.total_findings
                logger.info(
                    "Quality manifest appended: %d findings, %d degradations, "
                    "%d iterations, $%.4f cost",
                    manifest.total_findings, len(manifest.degradations),
                    manifest.iterations_completed, manifest.api_cost_usd,
                )
        except Exception:
            logger.warning("Quality manifest generation failed (non-fatal)", exc_info=True)
            metrics["manifest_appended"] = False

        return BlockResult(
            metrics=metrics,
            state_updates={"corpus_for_synthesis": swarm_report} if swarm_report else {},
        )
