# Copyright (c) 2025 MiroMind
# This source code is licensed under the Apache 2.0 License.

"""SynthesiserBlock -- final report generation phase.

The synthesiser reads the swarm-synthesised corpus and produces the
polished final report.  This block handles the post-synthesiser
cleanup: corpus state persistence, resource release, and quality
manifest generation (Phase 4).
"""

from __future__ import annotations

import logging

from models.pipeline_block import (
    BlockContext, BlockCriticality, BlockResult, ParamSpec,
    PipelineBlock,
)

logger = logging.getLogger(__name__)


class SynthesiserBlock(PipelineBlock):
    """Final phase: polish swarm output into the definitive report."""

    name = "synthesiser"
    needs_corpus = True
    criticality = BlockCriticality.CRITICAL
    is_looped = False

    input_specs = [
        ParamSpec(
            key="corpus_for_synthesis",
            expected_type=str,
            validator=lambda v: bool(v and len(v.strip()) > 50),
            description="Swarm-synthesised corpus (>50 chars)",
        ),
    ]
    output_specs = []  # Output goes to conversation history via ADK

    async def execute(self, ctx: BlockContext) -> BlockResult:
        """Post-synthesiser processing: manifest, measure, and cleanup.

        NOTE: The actual LLM call is handled by ADK's Agent.
        This block runs as the after_agent_callback wrapper.
        """
        state = ctx.state

        # Measure what the synthesiser had to work with
        swarm_input = state.get("corpus_for_synthesis", "")
        corpus_findings = 0

        if ctx.corpus is not None:
            try:
                corpus_findings = ctx.corpus.conn.execute(
                    "SELECT COUNT(*) FROM conditions WHERE row_type = 'finding'"
                ).fetchone()[0]
            except Exception:
                pass

        metrics = {
            "swarm_input_length": len(swarm_input) if swarm_input else 0,
            "corpus_findings": corpus_findings,
        }

        # ── Phase 4: Quality Manifest ──
        # Append computed provenance footer to the synthesis output.
        # NOT generated by LLM — computed from corpus state + pipeline metrics.
        try:
            from models.quality_manifest import QualityManifest
            manifest = QualityManifest.from_state(state)
            footer = manifest.format_footer()
            if footer and footer.strip():
                # Append to the synthesis output that the synthesiser will polish
                current_synthesis = state.get("corpus_for_synthesis", "")
                if current_synthesis:
                    state["corpus_for_synthesis"] = current_synthesis + footer
                metrics["manifest_appended"] = True
                metrics["manifest_degradations"] = len(manifest.degradations)
                metrics["manifest_findings"] = manifest.total_findings
                logger.info(
                    "Quality manifest appended: %d findings, %d degradations, "
                    "%d iterations, $%.4f cost",
                    manifest.total_findings, len(manifest.degradations),
                    manifest.iterations_completed, manifest.api_cost_usd,
                )
        except Exception:
            logger.warning("Quality manifest generation failed (non-fatal)", exc_info=True)
            metrics["manifest_appended"] = False

        return BlockResult(metrics=metrics)
