# Copyright (c) 2025 MiroMind
# This source code is licensed under the Apache 2.0 License.

"""QualityManifest -- computed provenance footer for every research output.

NOT generated by LLM — computed from corpus state + pipeline metrics.
Appended to every research report as a structured provenance section
so the reader knows exactly what the pipeline did and didn't do.

Shows:
- Total findings (scored, unscored, excluded)
- Source count and types
- Iteration count
- Degradations (failed APIs, scoring failures, etc.)
- Contradictions found
- Convergence status
- API cost (if tracked)
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field

logger = logging.getLogger(__name__)


@dataclass
class QualityManifest:
    """Structured provenance for a pipeline run."""

    # Corpus metrics
    total_findings: int = 0
    scored_findings: int = 0
    unscored_findings: int = 0
    excluded_findings: int = 0
    thought_count: int = 0
    contradiction_count: int = 0
    unique_sources: int = 0
    source_types: list[str] = field(default_factory=list)

    # Pipeline metrics
    iterations_completed: int = 0
    max_iterations: int = 0
    convergence_reached: bool = False
    evidence_sufficient: bool = False

    # Degradations (from ErrorEscalationAspect)
    degradations: list[dict] = field(default_factory=list)

    # API metrics
    api_cost_usd: float = 0.0
    apis_configured: int = 0
    apis_failed: list[str] = field(default_factory=list)
    apis_succeeded: list[str] = field(default_factory=list)

    @classmethod
    def from_state(cls, state: dict) -> "QualityManifest":
        """Build a manifest from pipeline state and corpus."""
        manifest = cls()

        # Pipeline metrics
        manifest.iterations_completed = state.get("_corpus_iteration", 0)
        manifest.api_cost_usd = state.get("_cumulative_api_cost", 0.0)
        manifest.degradations = state.get("_pipeline_degradations", [])

        # API validation results (Phase 5)
        api_health = state.get("_api_health", {})
        manifest.apis_configured = len(api_health)
        manifest.apis_failed = [
            name for name, status in api_health.items()
            if not status.get("reachable", True)
        ]
        manifest.apis_succeeded = [
            name for name, status in api_health.items()
            if status.get("reachable", True)
        ]

        # Corpus metrics (requires active corpus)
        try:
            from callbacks.condition_manager import _corpus_stores
            corpus_key = state.get("_corpus_key")
            if corpus_key and corpus_key in _corpus_stores:
                corpus = _corpus_stores[corpus_key]
                _populate_corpus_metrics(manifest, corpus)
        except Exception:
            logger.debug("QualityManifest: could not read corpus metrics")

        return manifest

    def format_footer(self) -> str:
        """Format the manifest as a human-readable provenance footer.

        This is appended to the final synthesiser output.
        """
        lines = [
            "",
            "---",
            "## Research Provenance",
            "",
        ]

        # Findings summary
        lines.append(f"**Findings:** {self.total_findings} total")
        if self.scored_findings:
            lines.append(f"  - {self.scored_findings} scored")
        if self.unscored_findings:
            lines.append(f"  - {self.unscored_findings} unscored (quality unknown)")
        if self.excluded_findings:
            lines.append(f"  - {self.excluded_findings} excluded (low quality/duplicates)")
        if self.contradiction_count:
            lines.append(f"  - {self.contradiction_count} contradictions detected")

        # Sources
        if self.unique_sources:
            lines.append(f"**Sources:** {self.unique_sources} unique")
        if self.source_types:
            lines.append(f"**Source types:** {', '.join(sorted(set(self.source_types)))}")

        # Pipeline execution
        lines.append(f"**Iterations:** {self.iterations_completed}")
        if self.convergence_reached:
            lines.append("**Exit reason:** Convergence detected (research saturated)")
        elif self.evidence_sufficient:
            lines.append("**Exit reason:** Evidence sufficient (thinker judgement)")
        else:
            lines.append(f"**Exit reason:** Max iterations reached ({self.iterations_completed})")

        # Degradations
        if self.degradations:
            lines.append(f"**Degradations:** {len(self.degradations)}")
            for d in self.degradations[:5]:
                lines.append(f"  - [{d.get('category', 'unknown')}] {d.get('source', '?')}: {d.get('error', '?')}")
            if len(self.degradations) > 5:
                lines.append(f"  - ... and {len(self.degradations) - 5} more")

        # API health
        if self.apis_failed:
            lines.append(f"**APIs unavailable:** {', '.join(self.apis_failed)}")

        # Cost
        if self.api_cost_usd > 0:
            lines.append(f"**Estimated API cost:** ${self.api_cost_usd:.4f}")

        lines.append("")
        return "\n".join(lines)


def _populate_corpus_metrics(manifest: QualityManifest, corpus: object) -> None:
    """Read corpus metrics directly from DuckDB."""
    conn = getattr(corpus, "conn", None)
    if conn is None:
        return

    try:
        manifest.total_findings = conn.execute(
            "SELECT COUNT(*) FROM conditions WHERE row_type = 'finding'"
        ).fetchone()[0]

        manifest.scored_findings = conn.execute(
            "SELECT COUNT(*) FROM conditions "
            "WHERE row_type = 'finding' AND score_version > 0"
        ).fetchone()[0]

        manifest.unscored_findings = conn.execute(
            "SELECT COUNT(*) FROM conditions "
            "WHERE row_type = 'finding' AND score_version = 0"
        ).fetchone()[0]

        manifest.excluded_findings = conn.execute(
            "SELECT COUNT(*) FROM conditions "
            "WHERE row_type = 'finding' AND consider_for_use = FALSE"
        ).fetchone()[0]

        manifest.thought_count = conn.execute(
            "SELECT COUNT(*) FROM conditions WHERE row_type = 'thought'"
        ).fetchone()[0]

        manifest.contradiction_count = conn.execute(
            "SELECT COUNT(*) FROM conditions "
            "WHERE contradiction_flag = TRUE AND consider_for_use = TRUE"
        ).fetchone()[0]

        # Unique sources
        try:
            manifest.unique_sources = conn.execute(
                "SELECT COUNT(DISTINCT source_ref) FROM conditions "
                "WHERE source_ref IS NOT NULL AND source_ref != ''"
            ).fetchone()[0]
        except Exception:
            pass

        # Source types
        try:
            rows = conn.execute(
                "SELECT DISTINCT source_type FROM conditions "
                "WHERE source_type IS NOT NULL AND source_type != ''"
            ).fetchall()
            manifest.source_types = [r[0] for r in rows]
        except Exception:
            pass

    except Exception:
        logger.debug("Failed to read corpus metrics for quality manifest")
